name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - azure
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - azure

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: src-pages
          fetch-depth: 10
          submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/coinStack/coinStack/wwwroot/css/

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.1
        with:
          source: coinStack/Styles/MyStyles.scss
          destination: /tmp/coinStack/coinStack/wwwroot/css/

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
          ref: pr-pages
          fetch-depth: 1

      - name: Move compiled CSS to path within pr-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add assets/css/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pr-pages

      - name: Initialize Pull pull_request
        uses: gha-utilities/init-pull-request@v0.0.4
        with:
          pull_request_token: $ {{ secrets.GITHUB_TOKEN }}
          head: pr-pages
          base: gh-pages
          title: 'Updates site files from latest Actions build'
          body: >
            insert description of latest features here

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_SMOKE_063C9C10F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "coinStack" # App source code path
          api_location: "coinStackAPI" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_SMOKE_063C9C10F }}
          action: "close"
